### ISSUE TITLE
Feedback - Week 11 Assignment

### ISSUE THREAD

**Issue by ntuvera** [stvbuller/Hangman#1]
hey @stvbuller, nice work on the Hangman app.  I know you're aware that .didWeFindTheWord was not working, but from what I'm reading it looks like a scope issue.  when you assign this.found to true that is only for that scope and deeper.

`
  this.didWeFindTheWord = function() {      
     this.lets.every(function(curLets) {  
       if (curLets.appear == true){       
         this.found = true;              // console.log(this.found) "true"
       }
  return this.found;                    // console.log(this.found) "false"
     });
`

`this.didWeFindTheWord = function() {
  this.found = this.lets.every(function(curLet) {
    return curLets.appear;   // console.log "true"
  });
  return this.found             // console.log "true"
}`

edit: formatting issues

**Comment by stbuller** [comment]
added a didWeFindTheWord function that works
